"""Raw user-action events captured for telemetry and user studies.

Deliberately **not** foreign-keyed to `users`, `datasets` or `images`. Study data
has to stay analysable after the dataset it was gathered on is deleted or an
account is removed, and a cascade would silently destroy the record of a session
that a paper depends on. The ids are kept as plain columns and resolved (or not)
at analysis time.

One row per event. `event_id` is generated by the client so a retried flush --
the common case, since the browser re-sends a batch that timed out -- is
de-duplicated instead of double-counted.
"""
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Index, Integer, String, Text

from app.database import database


class UserEvents(database):
    __tablename__ = "user_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    #: Client-generated UUID; unique so a replayed batch collapses into one row.
    event_id = Column(String(64), nullable=False, unique=True, index=True)

    #: When the event happened, as reported by its source (client clock for
    #: frontend events, server clock for backend ones).
    ts = Column(DateTime, nullable=False, index=True)
    #: When the server accepted it. The gap between the two measures client
    #: buffering delay and exposes a skewed client clock during analysis.
    received_at = Column(DateTime, nullable=False,
                         default=lambda: datetime.now(timezone.utc))

    #: Authenticated username, or NULL for events emitted before login.
    username = Column(String, nullable=True, index=True)
    #: Per browser-tab session (sessionStorage UUID), the unit a study run groups by.
    #: Not indexed on its own -- the composite (session_id, ts) below serves a
    #: lookup by session just as well, and this table is written far more often
    #: than it is read.
    session_id = Column(String(64), nullable=True)

    #: One of app.services.telemetry.config.TelemetryComponent.
    #: Likewise covered by the composite (component, ts) index below.
    component = Column(String(32), nullable=False)
    #: Dotted event name, e.g. "tool.switch", "contour.create", "ai.prompted.invoke".
    event_type = Column(String(128), nullable=False, index=True)
    #: "frontend" or "backend".
    source = Column(String(16), nullable=False)

    dataset_id = Column(Integer, nullable=True, index=True)
    image_id = Column(Integer, nullable=True, index=True)
    #: Set for anything that measures a span (AI inference, request handling,
    #: time spent on a route).
    duration_ms = Column(Integer, nullable=True)

    #: JSON-encoded event detail, truncated to USER_EVENTS_MAX_PAYLOAD_BYTES.
    payload = Column(Text, nullable=True)
    #: Client build/user-agent hint, so a study can separate browser effects.
    client = Column(String(255), nullable=True)

    __table_args__ = (
        # The two queries analysis actually runs: "everything for this session, in
        # order" and "this component over this window".
        Index("ix_user_events_session_ts", "session_id", "ts"),
        Index("ix_user_events_component_ts", "component", "ts"),
    )

    def as_dict(self) -> dict:
        """Flat representation used by the JSONL/CSV export."""
        return {
            "event_id": self.event_id,
            "ts": self.ts.isoformat() if self.ts else None,
            "received_at": self.received_at.isoformat() if self.received_at else None,
            "username": self.username,
            "session_id": self.session_id,
            "component": self.component,
            "event_type": self.event_type,
            "source": self.source,
            "dataset_id": self.dataset_id,
            "image_id": self.image_id,
            "duration_ms": self.duration_ms,
            "payload": self.payload,
            "client": self.client,
        }


#: Column order used by the CSV export, kept next to the model so the two cannot drift.
EXPORT_FIELDS = [
    "event_id", "ts", "received_at", "username", "session_id", "component",
    "event_type", "source", "dataset_id", "image_id", "duration_ms", "payload", "client",
]
