"""CSV round trip for image metadata.

Tagging forty images through a dialog is a demo; the workflow people actually
have is a spreadsheet. So the two halves here are deliberately symmetric:
:func:`export_csv` writes a file that :func:`import_csv` reads back unchanged.
With an untagged dataset the export is just a column of filenames — that is the
*template*, and starting from it is what makes the filenames match on the way
back in.

The importer never writes on the first pass. :func:`import_csv` with
``dry_run=True`` returns exactly what would happen — which rows matched, which
filenames it could not find, which images the file says nothing about, which keys
are new and what type each new column looks like — so the preview a curator
approves is generated by the same code that then does the work.
"""
from __future__ import annotations

import csv
import io
from logging import getLogger

from sqlalchemy.orm import Session

from app.database.images import Images
from app.exceptions import InvalidMetadataError
from app.services.database_access import image_metadata as metadata_db
from app.services.metadata_types import MetadataValueType, coerce, infer_type

logger = getLogger(__name__)

#: Header names accepted as "this column identifies the image". ``file_name``
#: first because that is what the export writes and what a human recognises.
_FILENAME_HEADERS = ("file_name", "filename", "file", "image")
_ID_HEADERS = ("image_id", "id")

#: Cap on rows read from one upload. A metadata CSV has one row per image; a file
#: an order of magnitude past any real dataset is a mistake or an attack, and
#: either way should be refused rather than streamed into memory.
MAX_ROWS = 100_000


def export_csv(db: Session, dataset_id: int) -> str:
    """Every image of the dataset as a CSV row: ``file_name`` plus one column per key.

    Includes images with no metadata (their cells are blank) and keys that are
    declared but unused (their column is empty). Both are deliberate: the export
    doubles as the template to fill in, and a template that omits the untagged
    images is useless for tagging them.
    """
    images = (
        db.query(Images)
        .filter(Images.dataset_id == dataset_id)
        .order_by(Images.file_name)
        .all()
    )
    metadata = metadata_db.get_metadata_for_dataset(db, dataset_id)

    used_keys = {key for entries in metadata.values() for key in entries}
    declared_keys = {row.key for row in metadata_db.list_keys(db, dataset_id)}
    keys = sorted(used_keys | declared_keys, key=str.lower)

    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(["file_name", *keys])
    for image in images:
        entries = metadata.get(image.id, {})
        writer.writerow([image.file_name, *(entries.get(key, "") for key in keys)])
    return buffer.getvalue()


def _read_rows(content: bytes) -> tuple[list[str], list[dict[str, str]]]:
    """Parse the upload into (headers, rows), tolerating a UTF-8 BOM.

    ``utf-8-sig`` matters more than it looks: Excel writes a BOM, and without
    stripping it the first header becomes ``\\ufefffile_name`` and every row fails
    to match — a confusing "nothing matched" for a file that looks correct.
    """
    try:
        text = content.decode("utf-8-sig")
    except UnicodeDecodeError:
        try:
            text = content.decode("latin-1")
        except UnicodeDecodeError:
            raise InvalidMetadataError("Could not read the file as text.")

    # Sniff the delimiter: European Excel writes semicolons, and a file that is
    # one column wide because the delimiter was wrong matches nothing.
    sample = text[:4096]
    try:
        dialect = csv.Sniffer().sniff(sample, delimiters=",;\t")
    except csv.Error:
        dialect = csv.excel

    reader = csv.DictReader(io.StringIO(text), dialect=dialect)
    headers = [(name or "").strip() for name in (reader.fieldnames or [])]
    if not headers:
        raise InvalidMetadataError("The file has no header row.")

    rows = []
    for index, row in enumerate(reader):
        if index >= MAX_ROWS:
            raise InvalidMetadataError(f"The file has more than {MAX_ROWS} rows.")
        rows.append({(k or "").strip(): (v or "").strip() for k, v in row.items()})
    return headers, rows


def _identifier_column(headers: list[str]) -> tuple[str, bool]:
    """Which column names the image, and whether it holds ids rather than names.

    :raises InvalidMetadataError: if no column looks like an image identifier.
    """
    lowered = {header.lower(): header for header in headers}
    for candidate in _FILENAME_HEADERS:
        if candidate in lowered:
            return lowered[candidate], False
    for candidate in _ID_HEADERS:
        if candidate in lowered:
            return lowered[candidate], True
    raise InvalidMetadataError(
        "No image column found. The first column must be named "
        f"one of: {', '.join(_FILENAME_HEADERS + _ID_HEADERS)}."
    )


def import_csv(
        db: Session,
        dataset_id: int,
        content: bytes,
        username: str | None = None,
        dry_run: bool = True,
        replace: bool = False,
) -> dict:
    """Apply a metadata CSV to a dataset, or report what applying it would do.

    Args:
        db: SQLAlchemy session.
        dataset_id: Dataset whose images the identifier column is matched against.
            Matching is scoped to the dataset, so a file naming an image in
            someone else's dataset reports as unmatched rather than editing it.
        content: The raw uploaded bytes.
        username: Account to record on the written rows.
        dry_run: When True (the default) nothing is written and the return value
            is the preview.
        replace: Treat each row as the image's complete metadata, deleting keys
            the file does not mention. Off by default: a CSV about ``site``
            should not wipe the ``notes`` someone added by hand.

    Returns:
        ``{matched, unmatched, missing_from_file, columns, written, removed,
        dry_run}`` where ``columns`` describes each metadata column — its key,
        whether the dataset already knows it, and for a new one the type inferred
        from the file's own values, which is what the preview offers to declare.

    :raises InvalidMetadataError: if the file is unreadable, has no identifier
        column, or holds a value that an already-declared key's type rejects.
    """
    headers, rows = _read_rows(content)
    identifier, by_id = _identifier_column(headers)
    metadata_columns = [header for header in headers
                        if header != identifier and header.strip()]
    if not metadata_columns:
        raise InvalidMetadataError("The file has no metadata columns beside the "
                                   f"'{identifier}' column.")

    images = db.query(Images).filter(Images.dataset_id == dataset_id).all()
    if by_id:
        index = {str(image.id): image for image in images}
    else:
        # Case-insensitive on the filename: Windows and macOS both hand back
        # names whose case does not survive a round trip through a spreadsheet.
        index = {image.file_name.lower(): image for image in images}

    matched: dict[int, dict[str, str]] = {}
    unmatched: list[str] = []
    for row in rows:
        raw = (row.get(identifier) or "").strip()
        if not raw:
            continue
        image = index.get(raw if by_id else raw.lower())
        if image is None:
            unmatched.append(raw)
            continue
        matched[image.id] = {
            column: row.get(column, "") for column in metadata_columns
        }

    missing_from_file = [
        image.file_name for image in images if image.id not in matched
    ]

    # Describe each column: known keys keep their declared type, new ones get a
    # type inferred from this file's values for the preview to confirm.
    existing = {row.key: row for row in metadata_db.list_keys(db, dataset_id)}
    columns = []
    key_types: dict[str, str] = {}
    for column in metadata_columns:
        key = metadata_db.normalize_key(column)
        values = [entries.get(column, "") for entries in matched.values()]
        descriptor = existing.get(key)
        if descriptor is not None:
            value_type = MetadataValueType(descriptor.value_type)
        else:
            value_type = infer_type(values)
            key_types[key] = value_type.value
        columns.append({
            "column": column,
            "key": key,
            "is_new": descriptor is None,
            "value_type": value_type.value,
            "filled": sum(1 for value in values if value),
        })

    # Validate everything before writing anything, so a typo in row 300 does not
    # leave rows 1-299 applied. Reported per column with the offending value, in
    # the same shape whether this is the dry run or the real one.
    errors: list[dict] = []
    for column_info in columns:
        column, key = column_info["column"], column_info["key"]
        options = list(existing[key].options or []) if key in existing else []
        for image_id, entries in matched.items():
            value = entries.get(column, "")
            if not value:
                continue
            try:
                coerce(value, column_info["value_type"], options)
            except InvalidMetadataError as exc:
                errors.append({"key": key, "value": value, "message": str(exc)})
                break  # One example per column is enough to fix the file.

    result = {
        "dry_run": dry_run,
        "matched": len(matched),
        "unmatched": unmatched[:50],
        "unmatched_count": len(unmatched),
        "missing_from_file": missing_from_file[:50],
        "missing_from_file_count": len(missing_from_file),
        "columns": columns,
        "errors": errors,
        "written": 0,
        "removed": 0,
    }

    if dry_run or errors or not matched:
        return result

    # One call per distinct set of values, which for a real CSV is one per image.
    # Grouping identical rows first would only help a file that repeats itself.
    written = removed = 0
    for image_id, entries in matched.items():
        outcome = metadata_db.set_metadata_for_images(
            db, [image_id],
            {metadata_db.normalize_key(k): v for k, v in entries.items()},
            username=username, replace=replace, key_types=key_types,
        )
        written += outcome["written"]
        removed += outcome["removed"]

    result["written"] = written
    result["removed"] = removed
    logger.info("Imported metadata for dataset %s: %s images, %s written.",
                dataset_id, len(matched), written)
    return result
